config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create]
  
  resources :tasks, only: [:new, :create, :edit, :update, :destroy]
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, length: {maximum: 30 }
  validates :status, presence: true, length: {maximum: 10}
  
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum:50 }
  validates :email, presence: true, length: { maximum:255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

  def counts(user)
    @count_tasks = user.tasks.count
  end

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました。'
      redirect_to @user
    else
      flash[:danger] = 'ログインできませんでした。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to '/'
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy]
  
  def new
    @task = current_user.tasks.build  # form_for 用
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save 
      flash[:success] = @count_tasks.to_s + 'タスクが正常に追加されました'
      redirect_to user_url(id: session[:user_id])
    else
      flash.now[:danger] = 'タスクが追加されませんでした'
      render :new
    end
  end

  def edit
  end
  
  def update
    if @task.update(task_params)
      flash[:success] = 'タスクは正常に更新されました'
      redirect_to user_url(id: session[:user_id])
    else
      flash[:danger] = 'タスクは更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    @task.destroy
    
    flash[:success] = 'タスクは正常に削除されました'
    @user = current_user
    redirect_to user_url(id: session[:user_id])
  end
  
  private
  
  def set_task
    @task = current_user.tasks.find_by(id: params[:id])
    redirect_to root_url unless @task
  end
  
  def task_params
    params.require(:task).permit(:content, :status)
    
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      redirect_to user_url(id: session[:user_id])
    else
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: :show

  def show
    @user = User.find_by(id: params[:id])
    @tasks = current_user.tasks.order('created_at').page(params[:page]).per(10)
    counts(@user)
    
    if (current_user != @user) || (@user==nil)
      redirect_to '/'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user =User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
    
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
  
end

app/helpers/toppages_helper.rb
module ToppagesHelper

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
  
  

app/views/layouts/_form.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">
    <%= form_for(task) do |f| %>
      <% if task.errors.any? %>
        <div class="alert alert-warning">
          <ul>
            <% task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :content, 'タスク' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :status, 'ステータス' %>
        <%= f.select :status, ["未着手", "進行中","完了"],{}, class: 'form-control'%>
      </div>
      
      <%= f.submit '送信', class: 'btn btn-primary'  %>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Tasklist</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
  
  
  
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_tasks' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_index.html.erb
<% task_num = 1 %>
<% if tasks.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="10%">No</th>
        <th width="60%">タスク</th>
        <th width="10%">状況</th>
        <th width="20%"></th>
      </tr>
    </thead>
    <tbody>
      <% tasks.each do |task| %>
        <tr>
          <td><%= task_num %></td>
          <td><%= task.content %></td>
          <td><%= task.status %></td>
          <td><%= link_to '編集', edit_task_path(task), class: "btn btn-warning" %>　<%= link_to '削除', task, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' }, class: 'btn btn-danger' %>
</td>          
        </tr>
        <% task_num += 1 %>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= paginate @tasks %>

<p></p>
<%= link_to '新規タスクの作成', new_task_path, class: "btn btn-primary" %>

app/views/tasks/_show.html.erb
<h1>id:<%= @task.id %>のタスク詳細</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @task.id %></td>
  </tr>
  <tr>
    <th>タスク</th>
    <td><%= @task.content %></td>
  </tr>
  <tr>
    <th>状況</th>
    <td><%= @task.status %></td>
  </tr>
</table>

<%= link_to 'このタスクについて編集する', edit_task_path(@task), class: 'btn btn-default' %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' }, class: 'btn btn-danger' %>

app/views/tasks/edit.html.erb
<div class="col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">
<h1>タスク編集</h1>
</div>

<%= render 'layouts/form', task: @task %>

app/views/tasks/new.html.erb
<div class="col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">
<h1>新規タスク作成</h1>
</div>

<%= render 'layouts/form', task: @task %>

app/views/tasks/show.html.erb
<h1>id:<%= @task.id %>のタスク詳細</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @task.id %></td>
  </tr>
  <tr>
    <th>タスク</th>
    <td><%= @task.content %></td>
  </tr>
  <tr>
    <th>状況</th>
    <td><%= @task.status %></td>
  </tr>
</table>

<%= link_to 'このタスクについて編集する', edit_task_path(@task), class: 'btn btn-default' %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' }, class: 'btn btn-danger' %>

app/views/toppages/index.html.erb
<div class="center jumbotron">
  <div class="text-center">
    <h1>Welcome to the Tasklist</h1>
    <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li><h1><%= link_to user_path(@user) do %>タスク一覧<span class="badge"><%= @count_tasks %></span><% end %></h1></li>
    </ul>
    <%= render 'tasks/index', tasks: @tasks %>
  </div>
</div>